dalibo/temboard-agent

docker/entrypoint.sh
To test this:
``` console
$ docker-compose down -v
$ make -C docker clean build
$ docker-compose up
$ docker-compose exec agent bash
```
``` console
^C
```
Go to https://0.0.0.0:8888/manage/instances
``` console
^C
```
Go to https://0.0.0.0:8888/server/0.0.0.0/2345/dashboard
=> Register update for UI dev env

MANIFEST.in, setup.py, temboard-agent.service
Since it's cross distro, install it anyway from pip, debian, rpm, etc.
Test it with at least jessie:
``` console
$ python setup.py sdist
$ sudo systemctl status temboard-agend
$ sudo pip install dist/temboad-agent....tar.gz
$ sudo systemctl daemon-reload
$ sudo systemctl status temboard-agend
```
Before installing, you have:
``` console
$ sudo systemctl status temboard-agent
● temboard-agent.service
Loaded: not-found (Reason: No such file or directory)
Active: inactive (dead)
```
After installation, you should get
```
● temboard-agent.service - temBoard agent for PostgreSQL
Loaded: loaded (/usr/local/lib/systemd/system/temboard-agent.service; disabled)
Active: inactive (dead)
```
This is enough to tell us that `temboard-agent.service` is properly loaded.
=> Install systemd unit from pip

setup.py
Test it with:
``` console
$ python setup.py --version
0.0.2.devX
$ git tag 0.4a1
$ python setup.py --version
0.0.4a1
```
This will ease creating dev snapshot.
=> Generate .devX version from git history

temboardagent/plugins/pgconf/__init__.py
TemBoard UI has now been updated to call agent with 'pgconf' routes.
https://github.com/dalibo/temboard/pull/110
Let's get rid of 'settings' forever.
=> Remove support for 'settings' in 'pgconf' routes

temboardagent/pluginsmgmt.py
Fixes:
FATAL: local variable 'fp_s' referenced before assignment
=> Ensure fp_s is defined

.coveragerc, requirement-ci.txt, temboardagent/__main__.py, temboardagent/cli.py, temboardagent/errors.py, temboardagent/logger.py, test/unit/test_cli.py
The purpose of this PR is:
- Add recoverable error management
- Ease setting exit code from program
- Distinguish unhandled error (i.e. bugs with traceback for report) from known user error
- Add debug mode dropping in pdb on unhandled error
- Graceful exit from debugger when dév adds a `set_trace`.
=> Error management

temboard-agent-adduser, temboardagent/agent.py, temboardagent/cli.py, temboardagent/configuration.py, temboardagent/register.py, temboardagent/utils.py, test/legacy/test/temboard.py, test/unit/test_agent_main.py, test/unit/test_configuration.py, test/unit/test_utils.py
This PR begins the big review of configuration management for #44 
The first steps are:
- Distinguish configuration from `ConfigParser`.
- Push arguments from CLI in configuration.
- Push defaults in configuration.
- Implement base API to define option and basic option marshalling
- Keep compatibility for the code base to avoid big rename everywhere.
=> Merge arguments and file in configuration

temboardagent/configuration.py
```
2017-11-08 22:29:15,107 temboard-agent[20206]: [httpd] INFO: SIGHUP signal caught, trying to reload configuration.
2017-11-08 22:29:15,108 temboard-agent[20206]: [httpd] ERROR: load_file() takes exactly 2 arguments (3 given)
2017-11-08 22:29:15,108 temboard-agent[20206]: [httpd] ERROR: Traceback (most recent call last):
2017-11-08 22:29:15,108 temboard-agent[20206]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 227, in httpd_run
2017-11-08 22:29:15,108 temboard-agent[20206]: [httpd] ERROR:     config = config.reload()
2017-11-08 22:29:15,108 temboard-agent[20206]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/configuration.py", line 263, in reload
2017-11-08 22:29:15,108 temboard-agent[20206]: [httpd] ERROR:     raise …
```
=> Fix error on reload

temboardagent/scripts/register.py
Fixes:
root@d0b3a81:/var/lib/temboard# gosu temboard temboard-agent-register --host agent96 --port 2345 --groups local_instances https://ui:8888
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/cli.py", line 41, in cli_wrapper
ERROR:     retcode = main(argv, environ) or 1
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/scripts/register.py", line 109, in main
ERROR:     args=args, environ=environ,
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/configuration.py", line 131, in load_configuration
ERROR:     config.load(args=args, environ=environ)
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/configuration.py", line 228, in load
ERROR:     self.add_values(iter_args_values(args)) …
=> Don't send args default to configuration

temboardagent/scripts/agent.py
Prevents errors with address_type failing to be determined
in multiprocessing.connection::Listener
=> Cast Taskmanager address and task_path to str

.gitignore, temboardagent/pluginsmgmt.py, temboardagent/scripts/agent.py, test/temboard-agent-sample-plugins/README.md, test/temboard-agent-sample-plugins/setup.py, test/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py, test/unit/test_plugins.py
cf. #131 
With this PR :
- temboardagent loads a plugin either new or legacy
- A missing plugin triggers a fatal error. This may be a typo
- A sample **external** plugin is available to test.
What's not yet here:
- extending configuration
- hot unload
- compatibility check from plugin
=> New plugin infrastructure

temboardagent/inventory.py, temboardagent/plugins/dashboard/metrics.py, test/legacy/test_dashboard.py
- linux distribution,
- os_version is now kernel version,
- cpu models with count for each model```
Here are the relevant changes:
Before:
```json
{
"os_version": "Linux 4.8.0-53-generic"
}
```
After:
```json
{
"os_version": "4.8.0-53-generic",
"linux_distribution": "debian 8.10",
"cpu_models": {
"Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz": 4
}
}
```
I prefered not to change the `os_version` keyword to avoid compatibility issues as much as possible. An other possibility would be to add a new keyword.
=> Add some information to metrics

.circleci/config.yml, test/legacy/Makefile, test/legacy/README.md, test/legacy/docker-compose.yml, test/legacy/run_tests_docker.sh
- don't use machine
- don't clone submodule, we use rpm
- don't build the same docker image
- don't fetch docker-compose
- don't run all tests in the same job
- don't test pg10 twice
- test rpm code instead of git code
=>  Fasten CI

.circleci/config.yml, test/legacy/Makefile, test/legacy/conftest.py, test/legacy/run_tests_docker.sh, test/legacy/test/temboard.py, test/legacy/test_activity.py, test/legacy/test_api.py, test/legacy/test_dashboard.py, test/legacy/test_monitoring.py, test/legacy/test_pgconf.py
- more robust
- easier to debug
- Start agent and Postgres once (saves about 20s per job).
=> Tests review

temboardagent/log.py, temboardagent/plugins/activity/__init__.py, temboardagent/scripts/agent.py, temboardagent/services.py
cf. #131 
This PR :
- adds hot load/unload of plugins in every processes
- set proctitle to every process
- clean exit on INT and TERM, pidfile is cleaned
- suicide on parent KILL
Logs with dalibo/temboard-sched#21 :
``` console
root@ece65fba2b23:/var/lib/temboard# DEBUG=1 sudo -u temboard temboard-agent                                                                                                                                                            
2018-04-04 16:41:13,926 [  437] [cli             ] DEBUG: Starting temBoard agent.                                                                                                                                                      
2018-04-04 16:41:13,928 [  437] [cli             ]  INFO: Reading …
```
=> Manage scheduler and workerpool processes

temboardagent/cli.py, test/unit/test_cli.py
cf. #131 
This allows to install a plugin after temboard-agent is started, and still activating it with `SIGHUP`.
=> Scan for new distributions before loading plugins

temboardagent/plugins/pgconf/functions.py
Fixes #238 
Currently in temBoard we rely on the setting units to tell whether the setting has changed and needs reload. For the `min_wal_size` or `max_wal_size`, the unit was retrieved using `current_setting('wal_segment_size')`.
`wal_segment_size` doesn't seem to differ from one version of postgres to an other. However, the `unit` has changed in recent versions. It's "16MB" in versions prior or equal to 9.6, whereas it's "MB" for earlier version.
Things may have change with this commit:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=9a3215026bd6955e88bd8c20542cfe6acffdb1c8
It seems more reliable to use the `unit` value given in `pg_settings` even for WAL sizes.
This fixes the issue with temBoard being confused when the value hasn't really changed.
See …
=> Don't use wal_segment_size as unit for wal_size

docker/Dockerfile, docker/entrypoint.sh, docker/pg_ctl_temboard.sh
Fixes https://github.com/dalibo/temboard/issues/397
While it works for `restart` or `stop`, the `docker` command doesn't have any `reload` command.
=> Docker - Call pg_ctl to reload/restart instance

docker/pg_ctl_temboard.sh
"/usr/local/bin" is not a universal path for pg_ctl.
For the postgres:9.6 docker image, it is available in "/usr/lib/postgresql/9.6/bin/".
This path is in root's PATH. I change the script to use.
It may look a bit ugly, but this is the only workaround I found.
Fixes https://github.com/dalibo/temboard/issues/272
=> Find pg_ctl in path

doc/core_api.rst, doc/dashboard_api.rst, doc/monitoring_api.rst, temboardagent/api.py, temboardagent/httpd.py, temboardagent/plugins/dashboard/__init__.py, temboardagent/plugins/monitoring/__init__.py, temboardagent/routing.py
This PR introduces a new way to protect access to some non-sensitives APIs.
Clients can now get access to dashboard and monitoring APIs without being authenticated with usual credentials: the agent key (the one configured in `temboard-agent.conf` file) can now be passed in query URL like `GET /dashboard?key=MYSECRETKEY`. In this case, `X-Session` header is not mandatory anymore. If the key is not configured in configuration file, then this authentication method is not allowed.
=> Authentication by key

temboardagent/httpd.py, temboardagent/plugins/dashboard/__init__.py, temboardagent/plugins/dashboard/metrics.py, temboardagent/postgres.py
With this PR, we:
- make sure that the agent continues to send metrics to the UI collector even if not connexion to Postgres is possible. In this case, only system metrics are sent with a global datetime.
- send the error message if any for http requests.
=> Stopped postgres

temboardagent/spc.py
Before the patch, the error message displayed in the logs was actually an erro code.
With the patch, we now correctly display the message.
Here what message[1] was in my case:
``` python
{'type': 'S', 'string': b'ERROR\x00VERROR\x00C42P01\x00Mrelation "pg_catalog.tables" does not exist\x00P32\x00Fparse_relation.c\x00L1159\x00RparserOpenTable\
x00\x00'}
```
Could this change between different versions of PostgreSQL?
=> Fix PG backend error handler

packaging/rpm/temboard-agent.spec
This reverts commit acf0bb46b3386d912cf119b3ea96a277558d2490.
=> Revert "rpm: Install global temboard-agent.conf only on RHEL6"

docker/Dockerfile, docker/Makefile, docker/docker-compose.dev.yml, docker/entrypoint.sh
I hit a bug in user management with different combination of docker uid.
Fixes:
```
agent_1       | + groupmod -g 998 docker
agent_1       | groupmod: group 'docker' does not exist
agent_1       | + catchall
agent_1       | + '[' 0 -lt 2 -a 6 -gt 0 ']'
agent_1       | + tail -f /dev/null
```
=> Docker fixes and updates

temboardagent/postgres.py, temboardagent/spc.py
SPC should raise an error if no password supplied with md5 auth. method
=> Fix #328 - backport v3

docs/installation.rst, temboardagent/scripts/register.py
Actually, just inject host and port argument to regular option marshaller.
Should fix #357
=> Read default agent host and port from configuration

share/auto_configure.sh
``` console
root@temboard:/# PGHOST=/var/run/postgresql/ PGPORT=5433 /usr/local/src/dalibo/temboard-agent-dev/share/auto_configure.sh https://ui.tba.docker:8888
...
Configuring temboard-agent to run on port 2346.
...
$
```
=> Natural increment of autoconfigured port

share/auto_configure.sh
The simplest use case is to use a dedicated postgresql user while still running as postgres. But we can also use a dedicated unix account, which is safer.
cc @Krysztophe
=> Separate system and postgresql user

docs/installation.rst
The default UI user has been specified in the docs (admin).
Specify that the registering user must be an administrator user from temBoard UI.
=> specify even more the difference between agent and UI users

docker-compose.yml, docker/Dockerfile
This way, we do not need to mount the "docker" binary from host to the
container.
This is essentially needed to make things work from temboard's docker
environment when using the docker.io package (on host) from Debian
instead of docker-ce from docker.com repository. See also respective
commit in temboard repository.
=> Install docker.io in Docker image

temboardagent/plugins/monitoring/__init__.py
This API is required for the pull mode to know if any collector end
point has been set up.
=> Add GET /monitoring/config API

docs/statements_api.rst, temboardagent/plugins/statements/__init__.py, tests/func/test_statements.py
Instead of returning the dbid and userid, we now return database name
and user name by joining the pg_stat_statements table on pg_authid and
pg_database.
=> Return username and dbname in statements plugin API

.circleci/config.yml, temboardagent/plugins/pgconf/functions.py, tests/func/Makefile, tests/func/docker-compose.yml, tests/func/test/configtest.py, tests/func/test/temboard.py, tests/func/test_pgconf.py, tests/unit/test_plugins_pgconf.py
See https://github.com/dalibo/temboard/issues/738
In Postgres 12, changes took place for some settings type. For example `autovacuum_vacuum_cost_delay` is now considered as real.
In temBoard we were correctly dealing with values written with a unit (for example '2ms') for settings of type integer. Settings of type real were considered to be written without a unit.
This PR makes sure that values with a unit are taken into account even if the setting is of type real.
At the same time, we need to handle values like '200us' since it is what '0.2ms' is converted to.
=> Support changes in types for some settings in PG12 (int -> real)

temboardagent/plugins/maintenance/functions.py
This prevent 'Task object is not subscriptable' error
This is due to commit https://github.com/dalibo/temboard-toolkit/commit/8f9781a822e038d949a3d03694c94bddb7d0c1c9#diff-d9d9c04dc55fd12ded3d694bc13823efR605
in temboard-toolkit
Fixes issues with maintenance tasks (reindex, vacuum, …) not being displayed in UI.
=> List of task return Task instances not dict

docker/Dockerfile, setup.py
Until we have regression tests on Python3.
Fixes:
Unhandled error:
Traceback (most recent call last):
File "/usr/local/src/temboard-agent/temboardagent/postgres.py", line 22, in __enter__
self.conn.connect()
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'connect'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/src/temboard-agent/temboardagent/toolkit/app.py", line 301, in entrypoint
retcode = self.main(argv, environ)
File "/usr/local/src/temboard-agent/temboardagent/scripts/agent.py", line 110, in main
self.apply_config()
File "/usr/local/src/temboard-agent/temboardagent/cli.py", line 68, in apply_config
return super(Application, self).apply_config()
File …
=> Switch back Dockerfile to Python 2

tests/func/test_api.py
This fixes failing tests after adding the statements plugin. See #436
=> Fix discover test, missing statements plugin

temboardagent/plugins/statements/__init__.py
This is helpful in order to know when the extension has not been loaded via preload_libraries.
=> Send the original error message

temboardagent/api.py, temboardagent/cli.py, temboardagent/plugins/activity/__init__.py, temboardagent/plugins/administration/__init__.py, temboardagent/plugins/dashboard/__init__.py, temboardagent/plugins/maintenance/__init__.py, temboardagent/plugins/monitoring/__init__.py, temboardagent/plugins/pgconf/__init__.py, temboardagent/plugins/statements/__init__.py, temboardagent/postgres.py, tests/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py
Agent will not fail starting if postgres isn't available yet
Compatibility with postgres version is checked for each plugin everytime
a connection is made. This should not be too expensive.
If an incompatibility is found, an error is logged but the agent continues to work.
=> Allow agent to start without postgres

temboardagent/plugins/pgconf/functions.py
To keep backwards compatibility with before the switch from tpc to psycopg2
This is an alternative to #449 and prevents us to modify temboard UI code.
This is probably safer.
=> Convert psycopg2 enums to coma separated strings

temboardagent/httpd.py
Like tornado does for UI. This helps naïve performance insights from
logs.
```
2020-08-19 16:23:49,583 [ 2111] [httpd           ]  INFO: client: 172.20.0.1 request: "GET /activity/waiting?key=key_for_agent HTTP/1.1" 200 - 112.30ms                                                             
```
=> Log request time in milliseconds

temboardagent/plugins/statements/__init__.py
It will be UI's job to select what it needs.
This avoids errors due to columns not available in different version of PG.
For example 'total_time' is 'total_exec_time' in PG13
=> Get all available columns from pg_stat_statements

temboardagent/httpd.py, temboardagent/postgres.py
We need to update imports from toolkit.utils to toolkit.pycompat accordingly.
(Extracted from #465.)
=> Update toolkit submodule

docker/Dockerfile, temboardagent/inventory.py
With this PR, we use python3.8 in dev environnement (docker image) and make sure dashboard plugin can work with this version.
=> python3 support

packaging/rpm/temboard-agent.spec
On CentOS 8, the openssl command produces a key file with 600 permission which
makes it unreadable by 'postgres' user and thus makes the systemd service file
fail to start the agent.
```console
$ sudo systemctl status temboard-agent-12-re7.service
● temboard-agent-12-re7.service - temBoard agent for PostgreSQL
Loaded: loaded (/etc/systemd/system/temboard-agent-12-re7.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Fri 2020-10-02 08:21:47 EDT; 7s ago
Process: 16704 ExecStart=/usr/bin/temboard-agent -c /etc/temboard-agent/temboard-agent-12-re7.conf -p /var/run/temboard/temboard-agent->
Main PID: 16707 (code=exited, status=1/FAILURE)
Oct 02 08:21:47 socle-centos8 temboardagent[16709]: [services] INFO: Starting …
```
=> Set read permission on SSL key file in RPM package

packaging/deb/Makefile, packaging/deb/mkdeb.sh
The real fix is in the last commit, which closes #477. Previous ones slightly improves the packaging code.
=> add psycopg2 as a proper dependency in Debian packaging

temboardagent/plugins/pgconf/functions.py, temboardagent/postgres.py
Most Exception objects have no 'message' attribute in Python 3.
This resolves this kind of errors in logs:
[taskmanager] ERROR:     data = metrics.get_metrics(app)
[taskmanager] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/plugins/dashboard/metrics.py", line 16, in get_metrics
[taskmanager] ERROR:     with app.postgres.connect() as conn:
[taskmanager] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/postgres.py", line 73, in __enter__
[taskmanager] ERROR:     raise UserError("Failed to connect to Postgres: %s" % e.message)
[taskmanager] ERROR: AttributeError: 'OperationalError' object has no attribute 'message'
=> Use str() for Exception instead of 'message' attribute for python3 compat

.circleci/config.yml, packaging/rpm/build.sh, packaging/rpm/temboard-agent.spec
From version 7.0, we already ship a RPM built with Python 3 on CentOS 8. Concerning CentOS 7, we have decided to keep the RPM package built with Python 2 because `python3-psycopg2` was not generally available on this platform (see https://github.com/dalibo/temboard-agent/pull/470#issuecomment-699800770). Further investigations/discussions showed that this package was actually available by EPEL or PGDG yum repositories. So in order to keep packaging consistent across CentOS releases, we here build the temboard-agent RPM package with python3 on centos7 as well. This means that users will need either EPEL or PGDG repository enabled to install the agent.
This change will affect temboard-agent version 7.1 and higher. This PR concerns v7 branch; after acceptance a similar one will be proposed …
=> Build RPM with python3 on CentOS 7

.circleci/config.yml, packaging/rpm/build.sh, packaging/rpm/temboard-agent.spec
This is a cherry-pick of 21d4e9edb44f52e2c552db3e31ac4878353404ad (now in v7 branch) upon which
the pkgrevision value of temboard-agent.spec got reset to '1' because we're on
the master branch, in preparation for version 8.0.
=> Build RPM with Python 3 on CentOS 7 (for master)

temboardagent/plugins/monitoring/probes.py
This should make the error message understandable, e.g. in #484.
=> Fix order of arguments in log message of SqlProbe

temboardagent/plugins/monitoring/probes.py
=> Include exception info in error log when SqlProbe fails to run

packaging/rpm/temboard-agent.spec
RPM package 7.1-2 got shipped to yum.dalibo.org/labs. Before the next 7.x
release, we need to restore the RPM package revision number to its previous
value. Follow-up on 21d4e9edb44f52e2c552db3e31ac4878353404ad.
=> Restore RPM pkgrevision to 1

packaging/deb/mkdeb.sh
This change will make sure that temboardagent package is installed in `python3/dist-packages` instead of `python3.x/dist-packages`.
This fixes issues with temboard not working on versions of unbuntu on which the version of python may not be 3.7.
=> Put packages in python3/dist-packages directory

packaging/deb/mkdeb.sh
Previously, as evidenced by the output of 'dpkg-deb -c' command in mkdeb.sh,
the .deb package contained .pyc files specific to the python version used at
build time (e.g.
./usr/lib/python3/dist-packages/temboardagent/__pycache__/routing.cpython-37.pyc).
This is problematic when then installing the package on a different python
version.
By calling pip install with --no-compile, we should hopefully avoid that.
=> Do not include .pyc files in Debian package

share/auto_configure.sh
Fixes #507
Prevents bash from catching an error because of '-u' set for error handling
Note : an 'unbound variable' error is caught on some version of bash
bash 4.2 on debian wheezy but not on bash 4.3 on debian jessie or up
On centOS, the error is raised whatever the version of bash is.
FIXME: there could be other solutions like using  when declaring the variable
=> Use default value for used port if none found

temboardagent/scripts/register.py
Since Python 3.6, json.loads() will try to decode a bytes content. For older
Python 3 version (e.g. 3.5 as available in Debian/stretch), this will fail with
a "the JSON object must be str, not bytes" TypeError. See commit
https://github.com/python/cpython/commit/b161562f72a28e83e62ec0a0a5de601e7724629f
in CPython.
To prevent this error, and hopefully make agent registration work on python
3.5, we decode the content of HTTP response ourselves.
Fixes #510.
=> Decode content before JSON loading in register

packaging/deb/temboard-agent.init
When the service is restarted with 'service temboard-agent restart', one can
see the following message:
start-stop-daemon: matching only on non-root pidfile /var/run/postgresql/temboard-agent.pid is insecure
We is a similar fix as
https://salsa.debian.org/debian/amavisd-new/-/commit/31cf737fd4d2c067ded79ffb812f04ce9393e185,
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921016
Note: this is untested.
=> Fix start-stop-daemon insecure error

temboardagent/inventory.py
The hostname detection code does not properly transform a byte string
to utf-8 with python 3 resulting in a failure do process the result of
execution of hostname -f.
=> Ensure that the result of hostname -f is decoded in python 3

temboardagent/plugins/monitoring/probes.py
In the replication_lag monitoring probe, the regex extracting values of non
quoted keyword=value parameters from primary_conninfo does not allow dot
and hypens, so it extract parts of ip addresses and fqdn, resulting in a
failed connection.
=> Fix parsing of primary_conninfo

temboardagent/plugins/monitoring/probes.py
psycopg2 handles better the parsing of keyword=value in
primary_connifo, saving us the work to manually check for the passfile
keyword, or lack of password and lookup of .pgpass, so use it for probes
related to replication.
=> Use psycopg2 to connect the upstream with primary_conninfo

temboardagent/plugins/monitoring/probes.py
When extracting the value of primary conninfo, some content can be
enclosing by single quotes. They must be quoted in recovery.conf with
backslashes or have signled doubled. Those backlashes must be removed
before using the connection string with psycopg2 (or libpq).
Closes #531
=> Unquote string when extracting primary_conninfo in probes

docs/requirements-doc.txt, packaging/deb/Makefile, packaging/deb/mkdeb.sh
Fixes:
$ temboard-agent --version
Traceback (most recent call last):
File "/usr/bin/temboard-agent", line 5, in <module>
from temboardagent.scripts.agent import main
File "/usr/lib/python3/dist-packages/temboardagent/scripts/agent.py", line 12, in <module>
from ..cli import Application
File "/usr/lib/python3/dist-packages/temboardagent/cli.py", line 6, in <module>
from .toolkit.app import BaseApplication
File "/usr/lib/python3/dist-packages/temboardagent/toolkit/app.py", line 5, in <module>
from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
=> Require distutils

packaging/deb/mkdeb.sh
Fix temboard-agent.init always installed on systemd systems.
Closes: #524
=> Check codename rather than systemctl presence

share/auto_configure.sh
Fixes Shellcheck:
In share/auto_configure.sh line 164:
default_cluster_name=${PGDATA##${home}/}
^-----^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.
=> Protect variable in expansion

temboardagent/httpd.py
This avoid sending key in logs.
=> Read key from HTTP header instead of query arg

temboardagent/plugins/monitoring/probes.py
Fixes: #567 
: Running instance probe replication_connection.
: syntax error at or near "CASE"
: LINE 2: CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS connected
:        ^
: Traceback (most recent call last):
=> Fix typo in replication lag query
