dalibo/temboard-agent

.gitignore, README.rst, docker-compose.yml
I need #3 to document dev env in README.rst
=> Provide quick dev env with docker compose

temboard-agent-register
Port of https://github.com/dalibo/temboard/pull/97.
=> Update agent registration for docker auto register

setup.py
This allow to have register command from pip install.
=> Install register command

docker/entrypoint.sh
Allow to register multiple agent exposing on different port.
=> Allow to customize public agent port for autoregister

CONTRIBUTING.rst, README.rst
This make README more PyPI friendly.
=> Split contributing out of README

setup.py
Fixes:
Collecting https://github.com/dalibo/temboard-agent/archive/master.zip
Downloading https://github.com/dalibo/temboard-agent/archive/master.zip
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-HWSNFf-build/setup.py", line 9, in <module>
subprocess.check_output(["git", "describe", "--tags"])
File "/usr/local/lib/python2.7/subprocess.py", line 212, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
errread, errwrite)
File "/usr/local/lib/python2.7/subprocess.py", line 1024, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
----------------------------------------
Command …
=> Rework version detection

setup.py
=> Install quickstart dumb users

temboardagent/__main__.py, temboardagent/errors.py
This PR provides:
- Nice handling of ConfigurationError, transparently.
- Nice message to user encountering bugs
=> Errors cont.

temboard-agent, temboard-agent-register, temboardagent/agent.py, temboardagent/logger.py
Logging handlers should be configured **once** and for `root` handler.
=> Configure logging once

temboardagent/agent.py, temboardagent/cli.py, temboardagent/options.py, temboardagent/register.py, test/unit/test_agent_main.py, test/unit/test_register_main.py
- argparse supersedesoptparse
- argparse gracefuly manage positional arguments
- move custom code near `main` code using it.
=> Move to argparse

temboard-agent, temboard-agent-register, temboardagent/httpd.py, test/legacy/test/temboard.py
@julmon merci d'avoir relancé, c'était effectivement pété à plus d'un titre.
=> Fix func tests

temboardagent/cli.py, temboardagent/configuration.py, temboardagent/log.py, test/unit/test_configuration.py
This PR provide:
- Color output on tty
- Mulitline format
- Restore shortname in log format
- Very simple format on stderr:
``` console
root@297a64962b50:/usr/local/src/temboard-agent# gosu temboard temboard-agent -c share/temboard-agent.conf
INFO: Loading plugin 'monitoring'.                              
INFO: Done.                                                                         
INFO: Loading plugin 'monitoring' configuration.
INFO: Done.                                                                       
INFO: Loading plugin 'dashboard'.
INFO: Done.                                          
INFO: Loading plugin 'pgconf' configuration.
ERROR: 'module' object has no attribute 'configuration'                       
```
- Extended format when debugging:
``` console …
```
=> Review log format for console

temboardagent/cli.py, temboardagent/configuration.py, temboardagent/scripts/agent.py, test/unit/test_configuration.py
``` console
root@297a64962b50:/usr/local/src/temboard-agent# TEMBOARD_CONFIGFILE=pouet gosu temboard ./temboard-agent
CRITI: Configuration file /usr/local/src/temboard-agent/pouet can't be opened.
root@297a64962b50:/usr/local/src/temboard-agent#
```
:-)
=> Loading environment variables

temboardagent/cli.py, temboardagent/configuration.py, temboardagent/scripts/agent.py, temboardagent/validators.py, test/legacy/test/temboard.py, test/unit/test_agent_main.py, test/unit/test_configuration.py, test/unit/test_validators.py
cf #44 
``` console
root@297a64962b50:/usr/local/src/temboard-agent# TEMBOARD_PORT=100000 DEBUG=y gosu temboard ./temboard-agent -c share/temboard-agent.conf
2017-09-29 10:08:29,713 [cli             ] DEBUG: Starting temBoard agent.
2017-09-29 10:08:29,714 [cli             ] CRITI: Invalid temboard_port from environ: 100000: Port out of range.
```
:-)
=> New file parser

docker/Dockerfile, docker/entrypoint.sh, temboardagent/configuration.py, temboardagent/scripts/adduser.py, temboardagent/scripts/agent.py, temboardagent/validators.py, test/unit/test_agent_main.py, test/unit/test_configuration.py, test/unit/test_validators.py
This PR migrate a bunch of options to new option API (called `OptionSpec`). This provide environment variable and clean code.
=> Move configuration to new validation

temboardagent/plugins/activity/functions.py, temboardagent/plugins/monitoring/probes.py
Update monitoring and activity plugins to support PostgreSQL 10 changes.
=> Add PostgreSQL 10 support

temboardagent/configuration.py, temboardagent/scripts/register.py, test/unit/test_register_main.py
=> Fix temboard-agent-register script

docker/Dockerfile
cf https://github.com/debuerreotype/debuerreotype/issues/10
=> docker: Workaround update-alternative behaviour with slim image

.circleci/config.yml, rpm/build.sh, rpm/docker-compose.yml
master : https://circleci.com/gh/dalibo/temboard-agent/940 : 42s
PR : https://circleci.com/gh/dalibo/temboard-agent/964 : 31s
local:
``` console
$ git checkout origin/master
$ time docker-compose run --rm centos7
...
real    2m24,527s
$ git pr 101
$ time docker-compose run --rm centos7
...
real    0m50,578s
$
```
=> Fasten rpm job

.circleci/config.yml, test/legacy/Makefile, test/legacy/docker-compose.yml, test/legacy/run_tests_docker.sh, test/legacy/test/temboard.py
:(
Now install from rpm works locally too. No hardcoded `/tmp/workspace`.
=> Fix test error detection

CONTRIBUTING.rst, README.rst, docker/Makefile, docker/README.md
- https://hub.docker.com/r/dalibo/temboard-agent/ now as a proper README and Dockerfile
- image is rebuilt on python image update
=> docker: Move to automated build

temboardagent/async.py, temboardagent/cli.py, temboardagent/scripts/agent.py
Before:
``` console
Démarrage de temboard-agent :  INFO: Reading /etc/temboard-agent/temboard-agent.conf.
INFO: Loading plugin 'monitoring'.
INFO: Done.
INFO: Loading plugin 'monitoring' configuration.
INFO: Done.
INFO: Loading plugin 'dashboard'.
INFO: Done.
INFO: Loading plugin 'dashboard' configuration.
INFO: Done.
INFO: Loading plugin 'pgconf'.
INFO: Done.
INFO: Loading plugin 'pgconf' configuration.
WARNI: No configuration: 'module' object has no attribute 'configuration'
INFO: Loading plugin 'administration'.
INFO: Done.
INFO: Loading plugin 'administration' configuration.
INFO: Done.
INFO: Loading plugin 'activity'.
INFO: Done.
INFO: Loading plugin 'activity' configuration.
WARNI: No configuration: 'module' object has no attribute 'configuration'
[  OK  ]
INFO: Reading …
```
=> Review startup logs

rpm/temboard-agent.init
``` console
[root@pg1 rpm]# ./temboard-agent status                                                                         
temboard-agent (pid  3523) en cours d'exécution...
[root@pg1 rpm]#
```
=> initrc: Restore status command

temboardagent/spc.py, test/unit/test_spc.py
=> Allow complex postgres versions number

docker/Dockerfile, docker/sudoers
=> docker: Keep env when using sudo

docker/Dockerfile
=> Make sure scheduler is installed

temboardagent/cli.py, temboardagent/postgres.py, test/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py, test/unit/test_postgres.py
=> Add Postgres object to manage Postgres instance

.editorconfig, docker-compose.yml, docker/Dockerfile, docker/entrypoint.sh, docker/sudoers
=> Docker fixes

doc/temboard-agent-configuration.rst, temboardagent/cli.py, temboardagent/log.py, test/unit/test_cli.py, test/unit/test_logging.py
=> Add --debug option

doc/temboardapi.py, temboardagent/cli.py, test/unit/test_cli.py
=> Document REST API for new plugins

.circleci/config.yml, setup.cfg, setup.py, temboardagent/plugins/activity/__init__.py, temboardagent/plugins/activity/functions.py
=> Migrate Activity plugin

Makefile, doc/contributing.rst, test/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py
- fix mulitplication of worker
- make redo_interval configurable
Chemin faisant, add a setting for redo_interval
=> Hellong task updates

temboardagent/cli.py, temboardagent/log.py, test/unit/pytest.ini, test/unit/test_logging.py
=> Debug logging fixes

temboardagent/cli.py, test/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py, test/unit/test_cli.py
cf. #131 
This PR includes:
- Hot loading of plugins
- Unloading of plugins
- Reload of logging configuration in main process
- Reload of Postgres object in main process
=> Plugin unload

temboardagent/daemon.py, temboardagent/httpd.py, temboardagent/scripts/agent.py, test/unit/test_agent_main.py
cf. #131 
This PR
- Uncouple service loop and request handling
- Gather signal and loop management.
To be continued
=> Refacto HTTPD

temboardagent/httpd.py, temboardagent/scripts/agent.py, temboardagent/services.py, temboardagent/utils.py
``` console
root@ece65fba2b23:/var/lib/temboard# ps -efH
UID        PID  PPID  C STIME TTY          TIME CMD
root        93     0  0 08:49 ?        00:00:00 bash
root      1499    93  0 09:12 ?        00:00:00   ps -efH
root        64     0  0 08:49 ?        00:00:00 bash
root      1480    64  0 09:12 ?        00:00:00   sudo -u temboard temboard-agent
temboard  1481  1480  8 09:12 ?        00:00:00     temboard-agent: main process
temboard  1483  1481  1 09:12 ?        00:00:00       python2 -m temboardagent.scripts.agent
temboard  1484  1481  1 09:12 ?        00:00:00       python2 -m temboardagent.scripts.agent
```
=> Extract Service class

temboardagent/configuration.py
Cf. #145 
Before :
``` console
root@ece65fba2b23:/var/lib/temboard# sudo -u nobody temboard-agent --debug
INFO: Reading /etc/temboard-agent/temboard-agent.conf.
CRITI: Not writable
root@ece65fba2b23:/var/lib/temboard#
```
After :
``` console
root@ece65fba2b23:/var/lib/temboard# sudo -u nobody temboard-agent 
INFO: Reading /etc/temboard-agent/temboard-agent.conf.
ERROR: Invalid temboard_home from config: Not writable...
CRITI: Failed to load configuration.
root@ece65fba2b23:/var/lib/temboard#
```
=> Fix validation message

test/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py
=> Migrate hellong to new HTTPD

temboardagent/configuration.py, test/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py, test/unit/test_configuration.py
=> Removable option specs

temboardagent/plugins/activity/__init__.py, temboardagent/plugins/administration/__init__.py, temboardagent/plugins/dashboard/__init__.py, temboardagent/plugins/dashboard/metrics.py, temboardagent/plugins/monitoring/__init__.py, temboardagent/plugins/pgconf/__init__.py, temboardagent/routing.py
=> Remove routes on unload

temboardagent/cli.py, temboardagent/scripts/agent.py, temboardagent/services.py, test/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py
Cf. #131 
In this PR :
- hellong background worker is remove
- hellong worker get current process app
- temboard plugins work as usual
- workers are updated only in worker pool process
- background tasks are updated only in scheduler process
=> Remove worker & background task

temboardagent/plugins/dashboard/__init__.py, temboardagent/plugins/monitoring/__init__.py, temboardagent/scripts/agent.py, temboardagent/services.py
=> Remove plugins workers on unload

temboardagent/cli.py, temboardagent/configuration.py, test/unit/test_configuration.py
=> Clean legacy configuration code

setup.py, temboardagent/cli.py, temboardagent/version.py, test/unit/test_core.py
- Distinguish master from latest release
- Log version on startup
- Log version with traceback
=> Ease track of running version

temboardagent/cli.py, temboardagent/configuration.py, temboardagent/httpd.py, temboardagent/plugins/monitoring/__init__.py, temboardagent/postgres.py, temboardagent/validators.py, test/legacy/test/configtest.py
cf. https://github.com/dalibo/temboard/issues/333
=> Various error

temboardagent/plugins/monitoring/__init__.py
cf. #207 
Before:
```
HTTP Error 500: Internal Server Error
Traceback (most recent call last):
File "/usr/local/src/temboard-agent/temboardagent/scheduler/taskmanager.py", line 809, in exec_worker
res = getattr(sys.modules[module], function)(*args, **kws)
File "/usr/local/src/temboard-agent/temboardagent/scripts/agent.py", line 99, in wrapper
return function(app=self.app, *a, **kw)
File "/usr/local/src/temboard-agent/temboardagent/plugins/monitoring/__init__.py", line 214, in monitoring_sender
raise e
HTTPError: HTTP Error 500: Internal Server Error
```
After:
```
Failed to send data to collector: Can't find the instance "instance.fqdn" in application.instances table.
You should find details in temBoard UI logs.
Failed to send data to collector.
Traceback (most recent call last):
File …
```
=> Improve collector management of HTTP Errors

.circleci/config.yml, docker/Dockerfile
=> Python 3, cont.

temboardagent/scripts/adduser.py, temboardagent/usermgmt.py
=> Accept empty lines in user file

temboardagent/api.py
=> Decode session username

docker/entrypoint.sh
cf. https://github.com/moby/moby/issues/35886
=> docker: Fix compose project with hyphen

temboardagent/plugins/monitoring/probes.py
Instead of collecting metrics for each cpu unit we collect the global one.
=> No need to collect metrics for each cpu unit

doc/core_api.rst, temboardagent/api.py, temboardagent/scripts/agent.py
Intends to fix https://github.com/dalibo/temboard/issues/39
=> Add /status API

.circleci/config.yml, doc/pgconf_api.rst, temboardagent/plugins/pgconf/__init__.py, temboardagent/plugins/pgconf/functions.py, test/legacy/Makefile, test/legacy/test_pgconf.py
Don't parse nor compare with configuration files
=> Use pg_settings only for configuration

docs/Makefile, docs/api.rst, docs/conf.py, docs/index.rst, docs/installation.rst, docs/temboard-agent-upgrade.rst
=> Review docs ToC

.circleci/config.yml, deb/temboard-agent@.service, share/auto_configure.sh
With this PR:
- propre logging for embedding in postinst
- switch from autostart to inline doc, just like postgres deb postinst
- support SysV-init systems
- Configure collector_url
- Various updates and fixes.
=> Auto configuration cont.

share/auto_configure.sh
=> Backport auto_configure.sh for CentOS

requirement-ci.txt, share/restart-all.sh
=> restart: Fix restart when no units are active

requirement-ci.txt, share/restart-all.sh
=> Fix restart with no active units

.circleci/config.yml, docs/installation.rst, packaging/rpm/build.sh, packaging/rpm/docker-compose.yml
=> docs: Fix typo in installation

Makefile, packaging/deb/mkdeb.sh, packaging/rpm/build.sh
=> Pen test toolkit submodule

Makefile, packaging/deb/mkdeb.sh, packaging/rpm/build.sh
=> Pentest toolkit submodule

temboardagent/spc.py
=> Configure encoding to server client_encoding parameter

temboardagent/plugins/maintenance/functions.py
=> Prevent ValueError in format for python2.6 - backport in v3

docs/maintenance_api.rst, temboardagent/plugins/maintenance/__init__.py, temboardagent/plugins/maintenance/functions.py
The goal of this pull request is to add support for maintenance operations not only on tables or indexes but also on database.
=> Maintenance database

docs/contributing.rst
=> Document submodule requirement

docs/upgrade.rst
To be cherry-picked in v4 branch.
=> Add upgrade doc from 3.X to 4.0

temboardagent/plugins/maintenance/functions.py, temboardagent/plugins/monitoring/probes.py
Backport.
Cherry-picked from 99c3
=> Improve btree_bloat SQL

docs/installation.rst
A few details in the installation doc, that should be more obvious to a novice user.
=> installation.md : more details for novice users

tests/func/test/configtest.py
=> Decode configuration files

packaging/rpm/temboard-agent.rpm.conf, share/auto_configure.sh, share/temboard-agent.conf
=> Hint conf.d overloading

temboardagent/plugins/maintenance/functions.py, temboardagent/plugins/monitoring/probes.py
This should solve #371 
Tested with agent on PG11 and PG12.
=> compatibility pg12 : update bloat query from ioguix + deal with oid removal

docs/installation.rst
From our discussion these last days, a big note in the installation note.
=> Explicit warning not to try anything other running on Linux and on the same instance

temboardagent/httpd.py, temboardagent/plugins/monitoring/__init__.py, temboardagent/plugins/monitoring/db.py, temboardagent/tools.py
This new API will be needed by the pull mode.
=> Add GET /monitoring API

docker/entrypoint.sh
This change allows to share a network between multiple compose project
with agent image running.
=> Read network name from .HostConfig.NetworkMode

docker/entrypoint.sh, docs/api.rst, docs/configuration.rst, docs/statements_api.rst, packaging/rpm/temboard-agent.rpm.conf, share/temboard-agent.conf, temboardagent/plugins/statements/__init__.py, tests/func/Makefile, tests/func/test/configtest.py, tests/func/test_statements.py
The completes the agent-side implementation of https://github.com/dalibo/temboard/issues/690.
=> Implement the statements API

docs/configuration.rst, packaging/rpm/temboard-agent.rpm.conf, temboardagent/cli.py
Per discussion at https://github.com/dalibo/temboard/issues/690#issuecomment-602444562
=> Enable the statements plugin by default

docs/installation.rst, temboardagent/scripts/register.py
This reverts commit 71f33e5373388935437a4654a9541472261c609f.
=> Revert "Default agent host and port in register helper"

temboardagent/plugins/statements/__init__.py, tests/func/test_statements.py
temBoard should be a good citizen and not reset statements stats itself
=> Don't call pg_stat_statements_reset

.editorconfig, temboardagent/cli.py, temboardagent/scripts/register.py, tests/func/test_scripts.py
Closes: #362 
Requires https://github.com/dalibo/temboard-toolkit/pull/26
=> temboard-agent-register update

docs/installation.rst, share/auto_configure.sh, share/purge.sh
=> Refuse to overwrite configuration

tests/unit/test_plugins_pgconf.py
fix for e7a959f4abd5d414130ef776a850ac3b39bdebbd
See https://github.com/dalibo/temboard-agent/pull/416#pullrequestreview-413074280
=> Remove unrequired assertion

temboardagent/plugins/maintenance/functions.py
This prevent 'Task object is not subscriptable' error
This is due to commit https://github.com/dalibo/temboard-toolkit/commit/8f9781a822e038d949a3d03694c94bddb7d0c1c9#diff-d9d9c04dc55fd12ded3d694bc13823efR605
in temboard-toolkit
=> List of task return Task instances not dict

setup.py
=> Install purge.sh in share directory

tests/func/conftest.py, tests/func/test/temboard.py, tests/func/test_activity.py, tests/func/test_api.py, tests/func/test_dashboard.py, tests/func/test_monitoring.py, tests/func/test_pgconf.py, tests/func/test_scripts.py
These commits make functional tests pass on my system (debian stable, python3.7, pg 11).
=> Adapt functional tests to work on Python 3 

temboardagent/api.py, tests/func/test_api.py
adding a func test for this endpoint along the way
=> expose block size setting in /discover api endpoint

docker/entrypoint.sh, docs/api.rst, docs/configuration.rst, docs/statements_api.rst, packaging/rpm/temboard-agent.rpm.conf, setup.py, share/temboard-agent.conf, temboardagent/cli.py, temboardagent/plugins/statements/__init__.py, tests/func/Makefile, tests/func/test/configtest.py, tests/func/test/temboard.py, tests/func/test_statements.py
This PR adds a new plugin which gets statistics from `pg_stat_statements`.
=> Statements

.circleci/config.yml, docker-compose.yml, docs/contributing.rst, packaging/rpm/temboard-agent.spec, temboardagent/api.py, temboardagent/cli.py, temboardagent/httpd.py, temboardagent/inventory.py, temboardagent/plugins/activity/functions.py, temboardagent/plugins/administration/functions.py, temboardagent/plugins/dashboard/metrics.py, temboardagent/plugins/maintenance/__init__.py, temboardagent/plugins/maintenance/functions.py, temboardagent/plugins/monitoring/__init__.py, temboardagent/plugins/monitoring/inventory.py, temboardagent/plugins/monitoring/probes.py, temboardagent/plugins/pgconf/functions.py, temboardagent/plugins/statements/__init__.py, temboardagent/postgres.py, tests/func/conftest.py, tests/func/run_tests_docker.sh, tests/func/test/temboard.py, tests/func/test_activity.py, tests/func/test_api.py, tests/func/test_dashboard.py, tests/func/test_monitoring.py, tests/func/test_pgconf.py, tests/temboard-agent-sample-plugins/temboard_agent_sample_plugins.py, tests/unit/test_postgres.py
Still use spc for replication connection as it's only available in
psycopg2 2.7+.
=> Move to psycopg2 2.5+

temboardagent/plugins/maintenance/functions.py
Fixes:
ERROR: dictionary update sequence element #0 has length 10; 2 is required
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/httpd.py", line 111, in response
ERROR:     (code, message) = self.route_request()
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/httpd.py", line 265, in route_request
ERROR:     return (200, func(http_context, self.app))
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/plugins/maintenance/__init__.py", line 50, in get_database
ERROR:     return dict(database, **{'schemas': schemas})
ERROR: ValueError: dictionary update sequence element #0 has length 10; 2 is required
ERROR: Internal error
=> Use queryone result directly

temboardagent/plugins/maintenance/functions.py
=> Use optimized btree bloat query (superuser édition)

packaging/rpm/temboard-agent.rpm.conf, share/temboard-agent.conf
cf. https://github.com/dalibo/temboard/issues/826
=> Update available probes

.circleci/config.yml, tests/func/Makefile, tests/func/conftest.py, tests/func/docker-compose.yml, tests/func/run_tests_docker.sh, tests/func/test_statements.py
=> Python3 backport

temboardagent/version.py
As discussed during today's meeting, I suggest to merge the (premature) v7 branch back into master.
This is simply the result of `git merge v7` and resolution of conflict in `temboardagent/version.py`.
=> Merge V7 branch in master

.circleci/config.yml, packaging/rpm/Makefile, packaging/rpm/README.rst, packaging/rpm/build.sh, packaging/rpm/docker-compose.yml, packaging/rpm/temboard-agent.spec, tests/func/Makefile
=> CentOS8 Packaging

packaging/rpm/Makefile
=> Don't require /dist/rpm before running make

temboardagent/plugins/statements/__init__.py
This should be configurable
Fixes #486
=> Don't assert dbname is 'postgres'

share/auto_configure.sh
=> Harden agent port autoconfiguration

temboardagent/plugins/monitoring/probes.py
- Fix spurious quotes for old query.
- Distinguish 9.5 and 9.6 query from older.
=> monit: Fix replication lag query

docs/core_api.rst, share/temboard-agent.conf
=> Adding missing statements in default conf

temboardagent/httpd.py, temboardagent/plugins/dashboard/db.py, temboardagent/plugins/monitoring/db.py, temboardagent/tools.py
=> Use custom json encoder

share/auto_configure.sh
=> Ignore .psqlrc in auto_configure.sh

temboardagent/inventory.py
=> Monitoring filesystems

temboardagent/scripts/agent.py
Add python, psycopg2 and libpq versions.
cf. #534
=> Expand temboard-agent --version

.circleci/config.yml, share/auto_configure.sh
=> auto_configure.sh improvements

share/auto_configure.sh
Ajout de LOGFILE configurable de manière identique au script `auto_configure.sh` utilisé côté serveur.
=> LOGFILE in auto_configure.sh

temboardagent/plugins/monitoring/probes.py
Looks like temboard does not accept UTC date from Python.
=> Get monitoring date from PostgreSQL
